const fs = require('fs');
const path = require('path');

const DIR = __dirname;
const BUNDLE_PATH = path.join(DIR, 'lessons-bundle.js');

function buildBundle() {
  const files = fs.readdirSync(DIR)
    .filter(f => f.endsWith('.md') && /^\d{2}/.test(f))
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));

  const bundle = {};
  const manifest = [];

  files.forEach(file => {
    try {
      const content = fs.readFileSync(path.join(DIR, file), 'utf8');
      bundle[file] = content;

      // 自動從 Markdown 第一行提取主標題 (# 標題)
      const firstLine = content.split('\n').find(line => line.trim().startsWith('# '));
      const cleanTitle = firstLine ? firstLine.replace(/^#\s*/, '').trim() : file.replace('.md', '');
      const idMatch = file.match(/^(\d{2}(?:\.\d)?)/);
      const id = idMatch ? idMatch[1] : file.replace('.md', '');

      // 自動分配難度級別標籤
      let level = '中階';
      if (id === '00' || id === '01.2') level = '全員';
      else if (id.startsWith('01')) level = '初階';
      else if (id === '02' || id === '03') level = '中階';
      else if (id === '04' || id === '05' || id === '06') level = '進階';
      else if (id === '07' || id === '08') level = '專家';

      manifest.push({
        id: id,
        file: file,
        title: cleanTitle,
        level: level,
        icon: getIconForId(id)
      });
    } catch(err) {
      console.error(`[Error] 讀取 ${file} 失敗:`, err);
    }
  });

  const outputJs = `// ⚡ 自動生成之課程目錄與數據包 (Auto-generated by watch-lessons.js)
window.LESSONS_MANIFEST = ${JSON.stringify(manifest, null, 2)};
window.LESSONS_DATA = ${JSON.stringify(bundle)};
`;

  fs.writeFileSync(BUNDLE_PATH, outputJs, 'utf8');
  console.log(`[${new Date().toLocaleTimeString()}] ✅ 已自動同步 ${manifest.length} 個 Markdown 模組到 HTML 系統！`);
}

function getIconForId(id) {
  const map = {
    '00': 'map',
    '01': 'git-branch',
    '01.1': 'car',
    '01.2': 'shield-alert',
    '02': 'target',
    '03': 'cpu',
    '04': 'bot',
    '05': 'users',
    '06': 'check-circle-2',
    '07': 'award',
    '08': 'sparkles'
  };
  return map[id] || 'file-text';
}

// 首次執行即時打包
buildBundle();

// 監聽目錄變更：若有新加、修改或刪除 .md 檔案，0.1 秒內自動同步
if (process.argv.includes('--watch')) {
  console.log('👀 正在監聽目錄中的 .md 檔案變動 (自動即時更新)...');
  let timeout = null;
  fs.watch(DIR, (eventType, filename) => {
    if (filename && filename.endsWith('.md') && /^\d{2}/.test(filename)) {
      clearTimeout(timeout);
      timeout = setTimeout(() => {
        console.log(`📝 偵測到 ${filename} 變動，自動重新生成目錄與內容...`);
        buildBundle();
      }, 150);
    }
  });
}
